version: '3'
services:

    #==================================#
    # KyLibrary (GIT + MAVEN + TOMCAT) #
    # Main steps :                     #
    #   1 - Git clone                  #
    #   2 - Maven package              #
    #   3 - Copy war files             #
    #   4 - Run Tomcat                 #
    #==================================#
    project:
      container_name: KyLibrary
      build:
        context: .
        dockerfile: Dockerfile
      network_mode: bridge
      external_links:
        - KyLibraryDB
      ports:
        - '18080:8080'
      restart: always