version: '3'
services:

    #=====================#
    # POSTGRESQL DATABASE #
    #=====================#
    postgres:
      image: postgres:latest
      ports:
        - '18081:5432'
      network_mode: bridge
      container_name: KyLibraryDB
      environment:
        POSTGRES_DB: kylibrary
        POSTGRES_USER: kybox
        POSTGRES_PASSWORD: kybox-db:kylibrary
      volumes:
        - './db:/docker-entrypoint-initdb.d'
      restart: always

    #==================================#
    # KyLibrary (GIT + MAVEN + TOMCAT) #
    # Main steps :                     #
    #   1 - Git clone                  #
    #   2 - Maven package              #
    #   3 - Copy war files             #
    #   4 - Run Tomcat                 #
    #==================================#
    project:
      container_name: KyLibrary
      build:
        context: .
        dockerfile: Dockerfile
      network_mode: bridge
      external_links:
        - KyLibraryDB
      ports:
        - '18080:8080'
      restart: always