
package fr.kybox.gencode;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-07-03T20:30:04.904+02:00
 * Generated source version: 3.2.4
 *
 */
public final class LibraryService_LibraryServicePort_Client {

    private static final QName SERVICE_NAME = new QName("dd7b026a-d6a2-4089-adb2-596ab0598c73", "LibraryWebService");

    private LibraryService_LibraryServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = LibraryWebService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        LibraryWebService ss = new LibraryWebService(wsdlURL, SERVICE_NAME);
        LibraryService port = ss.getLibraryServicePort();

        {
        System.out.println("Invoking createUser...");
        fr.kybox.gencode.CreateUser _createUser_parameters = null;
        fr.kybox.gencode.CreateUserResponse _createUser__return = port.createUser(_createUser_parameters);
        System.out.println("createUser.result=" + _createUser__return);


        }
        {
        System.out.println("Invoking loanReturn...");
        fr.kybox.gencode.LoanReturn _loanReturn_parameters = null;
        fr.kybox.gencode.LoanReturnResponse _loanReturn__return = port.loanReturn(_loanReturn_parameters);
        System.out.println("loanReturn.result=" + _loanReturn__return);


        }
        {
        System.out.println("Invoking extendBorrowing...");
        fr.kybox.gencode.BookBorrowed _extendBorrowing_parameter = null;
        fr.kybox.gencode.BookBorrowed _extendBorrowing__return = port.extendBorrowing(_extendBorrowing_parameter);
        System.out.println("extendBorrowing.result=" + _extendBorrowing__return);


        }
        {
        System.out.println("Invoking searchBook...");
        fr.kybox.gencode.SearchBook _searchBook_parameters = null;
        fr.kybox.gencode.SearchBookResponse _searchBook__return = port.searchBook(_searchBook_parameters);
        System.out.println("searchBook.result=" + _searchBook__return);


        }
        {
        System.out.println("Invoking login...");
        fr.kybox.gencode.Login _login_parameters = null;
        fr.kybox.gencode.LoginResponse _login__return = port.login(_login_parameters);
        System.out.println("login.result=" + _login__return);


        }
        {
        System.out.println("Invoking userBookList...");
        fr.kybox.gencode.UserBookList _userBookList_parameter = null;
        fr.kybox.gencode.UserBookListResponse _userBookList__return = port.userBookList(_userBookList_parameter);
        System.out.println("userBookList.result=" + _userBookList__return);


        }
        {
        System.out.println("Invoking unreturnedBookList...");
        fr.kybox.gencode.UnreturnedBookList _unreturnedBookList_parameters = null;
        fr.kybox.gencode.UnreturnedBookListResponse _unreturnedBookList__return = port.unreturnedBookList(_unreturnedBookList_parameters);
        System.out.println("unreturnedBookList.result=" + _unreturnedBookList__return);


        }

        System.exit(0);
    }

}
