package fr.kybox.gencode;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-07-03T20:30:05.016+02:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "dd7b026a-d6a2-4089-adb2-596ab0598c73", name = "LibraryService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface LibraryService {

    @WebMethod
    @WebResult(name = "createUserResponse", targetNamespace = "dd7b026a-d6a2-4089-adb2-596ab0598c73", partName = "response")
    public CreateUserResponse createUser(
        @WebParam(partName = "parameters", name = "createUser", targetNamespace = "dd7b026a-d6a2-4089-adb2-596ab0598c73")
        CreateUser parameters
    );

    @WebMethod
    @WebResult(name = "loanReturnResponse", targetNamespace = "dd7b026a-d6a2-4089-adb2-596ab0598c73", partName = "response")
    public LoanReturnResponse loanReturn(
        @WebParam(partName = "parameters", name = "loanReturn", targetNamespace = "dd7b026a-d6a2-4089-adb2-596ab0598c73")
        LoanReturn parameters
    );

    @WebMethod
    @WebResult(name = "bookBorrowed", targetNamespace = "dd7b026a-d6a2-4089-adb2-596ab0598c73", partName = "response")
    public BookBorrowed extendBorrowing(
        @WebParam(partName = "parameter", name = "bookBorrowed", targetNamespace = "dd7b026a-d6a2-4089-adb2-596ab0598c73")
        BookBorrowed parameter
    );

    @WebMethod
    @WebResult(name = "searchBookResponse", targetNamespace = "dd7b026a-d6a2-4089-adb2-596ab0598c73", partName = "response")
    public SearchBookResponse searchBook(
        @WebParam(partName = "parameters", name = "searchBook", targetNamespace = "dd7b026a-d6a2-4089-adb2-596ab0598c73")
        SearchBook parameters
    );

    @WebMethod
    @WebResult(name = "loginResponse", targetNamespace = "dd7b026a-d6a2-4089-adb2-596ab0598c73", partName = "response")
    public LoginResponse login(
        @WebParam(partName = "parameters", name = "login", targetNamespace = "dd7b026a-d6a2-4089-adb2-596ab0598c73")
        Login parameters
    );

    @WebMethod
    @WebResult(name = "userBookListResponse", targetNamespace = "dd7b026a-d6a2-4089-adb2-596ab0598c73", partName = "response")
    public UserBookListResponse userBookList(
        @WebParam(partName = "parameter", name = "userBookList", targetNamespace = "dd7b026a-d6a2-4089-adb2-596ab0598c73")
        UserBookList parameter
    );

    @WebMethod
    @WebResult(name = "unreturnedBookListResponse", targetNamespace = "dd7b026a-d6a2-4089-adb2-596ab0598c73", partName = "response")
    public UnreturnedBookListResponse unreturnedBookList(
        @WebParam(partName = "parameters", name = "unreturnedBookList", targetNamespace = "dd7b026a-d6a2-4089-adb2-596ab0598c73")
        UnreturnedBookList parameters
    );
}
